### ISSUE TITLE
とても使いやすいです

### ISSUE THREAD

**Issue by baron-tommy** [treetips/schemaspy-mysql#1]

**Comment by baron-tommy** [comment]
スターつけさせてもらいました

**Comment by treetips** [comment]
@baronTommy ありがとうございます。JDBCドライバとschemaspyのjarを内包する事で、プロパティファイルのみ編集すれば動くというシンプルな構成にしました。もしschemaspyが出力するhtmlをホスト側で取得したい場合はvolume mountするだけで取得する事も可能になっています。
