### ISSUE TITLE
HTMLをダウンロードしたい

### ISSUE THREAD

**Issue by baron-tommy** [treetips/schemaspy-mysql#3]
タイトル通りです。

下記コマンドではコンテナに入れずでした、HTMLの丸ごとダウンロードは可能でしょうか?

```bash
docker exec -ti schemaspy_nginx /bin/bash
```

**Comment by baron-tommy** [comment]
下記で入れました (すみません

```
docker exec -ti schemaspy_nginx /bin/sh
```

docker-compose.yml  で voluemeの設定をしてみましたがうまくできず...

**Comment by treetips** [comment]
@baronTommy

当初はボリュームコンテナにして出力されたhtmlはコンテナ内に隠蔽していましたが、やはりhtmlが欲しい場合があるようなので、ボリュームコンテナをやめ、単純にホストにマウントする形式に変更しました。

最新のmasterをpullした後、手順通りSchemaSpyを実行すると、htmlというフォルダが自動生成され、その中にDB定義書html群が出力されるように変更しました。

**Comment by baron-tommy** [comment]
対応ありがとうございます。
確認できました
