### ISSUE TITLE
multiple database 

### ISSUE THREAD

**Issue by sapisuper** [treetips/schemaspy-mysql#6]
Hi I just figure out how to set multiple dbname in this config file, it is possible ??

thanks

**Comment by treetips** [comment]
@sapisuper Thank you for contacting me.

The current schemaspy does not seem to support multiple databases. 😢 

It seems that the [Sample Output](http://schemaspy.org/sample/index.html) does not have a UI that allows multiple databases to be viewed at the same time.

I think there are a few ways to deal with this.

* Clone this repository as many dbname's as you want, although it's redundant.
* Without using schemaspy.properties, execute java command with command element of docker-compose.yml as many as db.

**Comment by sapisuper** [comment]
@treetips thanks man , appreciate it!
